name: GKE Deploy Template

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

env:
  PROJECT_ID: probestack-prod
  ARTIFACT_REPO: probestack-prod-apps
  ARTIFACT_REGISTRY: us-central1-docker.pkg.dev
  GKE_CLUSTER: probestack-zonal-cluster
  GKE_LOCATION: us-central1-a
  GKE_LOCATION_FLAG: --zone
  NAMESPACE: secure-production-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      SERVICE_NAME: ${{ inputs.service_name }}
      IMAGE_TAG: ${{ inputs.image_tag }}

    steps:
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/861433193200/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-deployer@probestack-prod.iam.gserviceaccount.com

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Install GKE auth plugin
        run: gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER \
          $GKE_LOCATION_FLAG $GKE_LOCATION \
          --project $PROJECT_ID

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/$SERVICE_NAME \
          $SERVICE_NAME=$ARTIFACT_REGISTRY/$PROJECT_ID/$ARTIFACT_REPO/$SERVICE_NAME:$IMAGE_TAG \
          -n $NAMESPACE

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/$SERVICE_NAME \
          -n $NAMESPACE

      - name: Verify pods
        run: |
          kubectl get pods -n $NAMESPACE
