name: GKE Build Template

on:
  workflow_call:
    inputs:
      project_id:
        required: true
        type: string
      artifact_repo:
        required: true
        type: string
      artifact_registry:
        required: true
        type: string
      service_name:
        required: true
        type: string
      workload_identity_provider:
        required: true
        type: string
      service_account:
        required: true
        type: string

    outputs:
      image_tag:
        description: "Built image tag"
        value: ${{ jobs.build.outputs.image_tag }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/861433193200/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-deployer@probestack-prod.iam.gserviceaccount.com
          token_format: access_token

      - uses: google-github-actions/setup-gcloud@v2

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.artifact_registry }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - uses: docker/setup-buildx-action@v3

      - name: Generate Image Tag
        id: meta
        run: echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          provenance: false
          tags: |
            ${{ inputs.artifact_registry }}/${{ inputs.project_id }}/${{ inputs.artifact_repo }}/${{ inputs.service_name }}:${{ steps.meta.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
