name: Kong Konnect Reusable Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

      kong_config_path:
        required: true
        type: string

      control_plane_name:
        required: true
        type: string

      deck_version:
        required: false
        type: string
        default: "1.43.0"

      validate_only:
        required: false
        type: boolean
        default: false

    secrets:
      konnect_token:
        required: true

jobs:
  kong-deploy:
    name: Kong Konnect Deployment
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      #######################################################
      # Install decK
      #######################################################

      - name: Install decK
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v${{ inputs.deck_version }}/deck_${{ inputs.deck_version }}_linux_amd64.tar.gz -o deck.tar.gz

          tar -xzf deck.tar.gz

          sudo mv deck /usr/local/bin/deck

          deck version

      #######################################################
      # Validate
      #######################################################

      - name: Validate Kong Configuration
        run: |
          deck gateway validate \
            --konnect-token "${{ secrets.konnect_token }}" \
            --konnect-control-plane-name "${{ inputs.control_plane_name }}" \
            "${{ inputs.kong_config_path }}"

      #######################################################
      # Diff
      #######################################################

      - name: Diff Kong Configuration
        run: |
          deck gateway diff \
            --konnect-token "${{ secrets.konnect_token }}" \
            --konnect-control-plane-name "${{ inputs.control_plane_name }}" \
            "${{ inputs.kong_config_path }}"

      #######################################################
      # Sync
      #######################################################

      - name: Sync Kong Configuration
        if: ${{ inputs.validate_only == false }}
        run: |
          deck gateway sync \
            --konnect-token "${{ secrets.konnect_token }}" \
            --konnect-control-plane-name "${{ inputs.control_plane_name }}" \
            "${{ inputs.kong_config_path }}"
